### ISSUE TITLE
Works on PC, not on Server

### ISSUE THREAD

**Issue by jontobonto** [Techcatchers/PyLyrics-Extractor#6]
I need this for my Discord Bot so I can create a lyrics command, the code works when I use it on my pc but in the command, it does not work as expected. Always raises 

lyrics_extractor.lyrics.LyricScraperException: {'error': 'No results found'}

**Comment by jontobonto** [comment]
not just in the command just everywhere on server, in shell, as a script or in command

**Comment by Techcatchers** [comment]
Could you share the entire stack trace for this?

**Comment by jontobonto** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/xino/cogs/meta.py", line 398, in lyrics
    data = extract_lyrics.get_lyrics(song)
  File "/usr/local/lib/python3.8/dist-packages/lyrics_extractor/lyrics.py", line 195, in get_lyrics
    raise LyricScraperException({"error": "No results found"})
lyrics_extractor.lyrics.LyricScraperException: {'error': 'No results found'}```

**Comment by jontobonto** [comment]
or do you mean the code i'm using?

btw, server is running linux ubuntu 20.04

**Comment by Techcatchers** [comment]
Have you followed the steps to generate the API keys as stated in the
readme? Also, have you tried other song names too?

**Comment by jontobonto** [comment]
I followed the steps and it is working on my local pc but not on my server, I also tried on other servers too
I tried about 5 names and every worked on pc, no one on any server

**Comment by Techcatchers** [comment]
Can you check if all the dependencies are installed correctly on your
server?

Also, check specifically do you have this parser installed?

pip install lxml


P.S: Use pip or pip3 based on the version you are using.
P.P.S: Do let me know if this worked, I'll update the library accordingly.

**Comment by jontobonto** [comment]
I checked both parser & dependencies, everything is installed.
Also tried to install lxml, its up2date as well
![image](https://user-images.githubusercontent.com/67862800/97896726-c6294e00-1d35-11eb-965c-e82f9019ae20.png)
sadly still not working

**Comment by Techcatchers** [comment]
OK, clone this repo on your server from GitHub and try to debug separately
there.

You'll most likely get to know where the problem lies.

**Comment by jontobonto** [comment]
okay, i'll do
Thank you :)

**Comment by ghost** [comment]
Probably too late to answer but according to my research this happens when you use genius to extract lyrics in vps. Genius has some verification or something which makes it unusable in vps most likely.
